name: Build and Package with jpackage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [ '23' ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    # Set up JDK 23 (required for jpackage and since jlink doesn't currently support 23)
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '23'
    # Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle
    # Build the project using Gradle
    - name: Build core project with Gradle
      run: ./gradlew :clean :core:build# Upload artifact (signed or unsigned installers)
    # Upload artifact (signed or unsigned installers)
    - name: Upload signed or unsigned installers
      uses: actions/upload-artifact@v3
      with:
        name: installers-${{ runner.os }}
        path: core/build/jpackage/*
