name: JPackage and Code Signing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Change to 'windows-latest' or 'macos-latest' based on your target OS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK (required for jpackage)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '21'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Build the core project with Gradle
      - name: Build core project with Gradle
        run: ./gradlew :core:clean :core:build

      # Run jpackage on the core subproject
      - name: Package core project with jpackage
        run: ./gradlew :core:jpackage

      # Code sign the executables based on the OS
      - name: Code signing for Windows (if applicable)
        if: runner.os == 'Windows'
        run: |
          signtool sign /f ${{ secrets.CERTIFICATE_PFX }} /p ${{ secrets.CERTIFICATE_PASSWORD }} /tr http://timestamp.digicert.com /td sha256 /fd sha256 "core/build/jpackage/*.exe"

      - name: Code signing for macOS (if applicable)
        if: runner.os == 'macOS'
        run: |
          security create-keychain -p mypassword build.keychain
          security import ${{ secrets.CERTIFICATE_P12 }} -k build.keychain -P ${{ secrets.CERTIFICATE_PASSWORD }} -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security unlock-keychain -p mypassword build.keychain
          codesign --deep --force --verbose --sign "Developer ID Application: Your Name (Team ID)" core/build/jpackage/*.app
          codesign --deep --force --verbose --sign "Developer ID Application: Your Name (Team ID)" core/build/jpackage/*.pkg

      # Upload artifact (signed installer)
      - name: Upload signed installers
        uses: actions/upload-artifact@v3
        with:
          name: signed-installers
          path: core/build/jpackage
